name: goreleaser

on:
  push:
    tags:
      - v*

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: 0.x
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate release tarball
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          tar czf gemget-${VERSION}.tar.gz --transform "s,^,gemget-${VERSION}/," --exclude dist *
      - name: Upload release tarball
        uses: softprops/action-gh-release@master
        with:
          files: gemget-*.tar.gz
          append_body: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REPOS }}
